import { NextResponse } from "next/server";

const SYSTEM_INSTRUCTION = `
You are an AI Co-Designer assistant for a web-based design canvas. 
Your job is to read the user's design command and translate it into a JSON containing:
1. "reply": A short, friendly confirmation message in Indonesian of what actions you took.
2. "commands": An array of commands to execute on the canvas.

You MUST only call the tools listed below. DO NOT make up tools.
If you cannot perform the request with the tools below, return an empty "commands" array and explain it in "reply".

Available Tools:

1. changeBackgroundColor
   args: { "color": string }  // Sets the canvas background color. Supports HEX (e.g., "#22e605"), rgb, or color names.

2. addText
   args: {
     "text": string,          // The text content to write
     "fill": string,          // (Optional) Text color in HEX. Default "#000000".
     "fontSize": number       // (Optional) Font size. Default 32.
   }

3. addRectangle
   args: {
     "width": number,         // Width in pixels. Default 150.
     "height": number,        // Height in pixels. Default 100.
     "fill": string           // (Optional) Fill color in HEX. Default "#22e605".
   }

4. addCircle
   args: {
     "radius": number,        // Radius in pixels. Default 50.
     "fill": string           // (Optional) Fill color in HEX. Default "#10b981".
   }

5. clearCanvas
   args: {}                   // Removes all elements from the canvas except the background.

Ensure all outputs are valid JSON matching this schema:
{
  "reply": "string explaining what was done",
  "commands": [
    {
      "tool": "changeBackgroundColor" | "addText" | "addRectangle" | "addCircle" | "clearCanvas",
      "args": { ... }
    }
  ]
}

Example input: "Ganti background jadi biru dan ketik diskon gede"
Example output:
{
  "reply": "Saya telah mengubah warna background menjadi biru dan menambahkan teks 'diskon gede'.",
  "commands": [
    {
      "tool": "changeBackgroundColor",
      "args": { "color": "#0000ff" }
    },
    {
      "tool": "addText",
      "args": { "text": "diskon gede", "fill": "#ffffff", "fontSize": 36 }
    }
  ]
}
`;

export async function GET(request: Request) {
  // Check if API key is configured
  const apiKey = process.env.GEMINI_API_KEY;
  return NextResponse.json({ configured: !!apiKey });
}

export async function POST(request: Request) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return NextResponse.json(
        {
          error: "GEMINI_API_KEY is not configured in backend environment variables.",
          reply: "Mohon maaf, API Key Gemini belum diatur oleh developer. Silakan konfigurasikan file .env.local terlebih dahulu.",
        },
        { status: 500 }
      );
    }

    const { prompt } = await request.json();

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    // Call Google Gemini 1.5 Flash API directly using HTTP fetch
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [{ text: prompt }],
          },
        ],
        generationConfig: {
          responseMimeType: "application/json",
        },
        systemInstruction: {
          parts: [{ text: SYSTEM_INSTRUCTION }],
        },
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      return NextResponse.json(
        { error: `Gemini API returned an error: ${response.statusText}`, details: errText },
        { status: response.status }
      );
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      return NextResponse.json({ error: "Gemini did not return any content." }, { status: 500 });
    }

    // Parse the JSON response generated by Gemini
    const result = JSON.parse(generatedText.trim());
    return NextResponse.json(result);

  } catch (error: any) {
    console.error("Gemini API Route Error:", error);
    return NextResponse.json(
      { error: "Internal Server Error", message: error.message },
      { status: 500 }
    );
  }
}
